/**
 * The 500-feature platform catalogue.
 *
 * This is an opportunity inventory, not a shipped-feature list — items
 * 1–340 are horizontal capabilities every tenant's kernel can carry, and
 * 341–500 are industry-pack capabilities layered on the same kernel.
 *
 * It exists as typed data rather than CMS content for one reason: the
 * industry explorer on /features, the provisioning wizard in the admin
 * console and the activation sheet a customer signs should all be reading
 * the same list. Three copies of a 500-row catalogue would disagree within
 * a month.
 *
 * `pack: null` means horizontal — available to every industry. A pack name
 * means the capability only appears when that pack is licensed.
 */

export interface Feature {
  id: number;
  title: string;
  blurb: string;
  /** Category heading, e.g. "Opportunities and Pipeline". */
  group: string;
  /** Top-level division: "crm" | "erp" | "pack". */
  domain: "crm" | "erp" | "pack";
  /** Industry pack name, or null for horizontal capabilities. */
  pack: string | null;
}

type Row = [number, string, string];

function group(
  name: string,
  domain: Feature["domain"],
  pack: string | null,
  rows: Row[],
): Feature[] {
  return rows.map(([id, title, blurb]) => ({
    id,
    title,
    blurb,
    group: name,
    domain,
    pack,
  }));
}

export const FEATURES: Feature[] = [
  ...group("Universal CRM Foundation", "crm", null, [
    [1, "Unified Account Profiles", "Consolidate organizations, locations, ownership, and commercial history in one record."],
    [2, "Individual Contact Profiles", "Maintain complete identities, preferences, roles, and relationship histories."],
    [3, "Household and Group Records", "Model families, partnerships, committees, and other non-corporate groups."],
    [4, "Relationship Graph", "Visualize connections among people, companies, assets, deals, and cases."],
    [5, "Configurable Business Objects", "Create industry-specific record types without changing application code."],
    [6, "Flexible Field Library", "Support text, currency, dates, formulas, references, files, and structured values."],
    [7, "Record-Type Templates", "Give different business processes tailored fields, layouts, and requirements."],
    [8, "Configurable Lifecycle Models", "Define the stages each customer, asset, or engagement passes through."],
    [9, "Duplicate Detection and Merge", "Identify overlapping records and preserve the strongest combined history."],
    [10, "Chronological Record Timeline", "Present every interaction, change, document, and transaction in context."],
  ]),
  ...group("Lead and Account Management", "crm", null, [
    [11, "Multi-Source Lead Capture", "Ingest prospects from forms, imports, referrals, APIs, and communications."],
    [12, "Qualification Frameworks", "Apply configurable criteria for fit, need, authority, timing, and readiness."],
    [13, "Lead Scoring Rules", "Rank prospects using profile, behavior, engagement, and business-specific signals."],
    [14, "Automated Lead Assignment", "Route new leads by territory, capacity, specialization, or customer segment."],
    [15, "Lead Holding Queues", "Retain unassigned prospects in governed team queues with response deadlines."],
    [16, "Territory Management", "Organize ownership by geography, vertical, product, account tier, or custom criteria."],
    [17, "Account Hierarchies", "Represent parent companies, subsidiaries, branches, franchises, and operating units."],
    [18, "Strategic Account Plans", "Track objectives, stakeholders, risks, whitespace, and planned engagement."],
    [19, "Buying Committee Mapping", "Record decision-makers, influencers, blockers, users, and commercial sponsors."],
    [20, "Contact Role Management", "Define each participant's role separately for every deal or engagement."],
  ]),
  ...group("Opportunities and Pipeline", "crm", null, [
    [21, "Multi-Pipeline Management", "Run distinct sales processes for products, services, regions, or industries."],
    [22, "Visual Opportunity Board", "Move deals through stages using a configurable drag-and-drop workspace."],
    [23, "Guided Sales Stages", "Require appropriate evidence and actions before opportunities can advance."],
    [24, "Opportunity Product Lines", "Associate quantities, terms, pricing, and expected revenue with each deal."],
    [25, "Deal Team Management", "Assign owners, specialists, partners, and executives with explicit responsibilities."],
    [26, "Revenue Split Allocation", "Divide deal credit among contributors without duplicating forecast value."],
    [27, "Weighted Pipeline Forecasting", "Calculate expected revenue using probability, amount, and projected timing."],
    [28, "Forecast Category Controls", "Classify deals as pipeline, upside, committed, omitted, or custom categories."],
    [29, "Deal Health Indicators", "Surface inactivity, stakeholder gaps, delayed milestones, and commercial risks."],
    [30, "Win-Loss Reviews", "Capture structured reasons, competitors, lessons, and follow-up opportunities."],
  ]),
  ...group("Pricing, Quotes, and Revenue", "crm", null, [
    [31, "Product and Service Catalog", "Maintain standardized offerings, options, units, and availability rules."],
    [32, "Multiple Price Books", "Apply different pricing by market, segment, partner, currency, or contract."],
    [33, "Configurable Product Bundles", "Combine compatible products, services, add-ons, and required dependencies."],
    [34, "Discount Guardrails", "Enforce margin thresholds and approval requirements before discounts are offered."],
    [35, "Quote Builder", "Produce governed quotes from approved products, prices, taxes, and commercial terms."],
    [36, "Proposal Generation", "Assemble branded proposals from CRM data, templates, and reusable content."],
    [37, "Subscription Tracking", "Manage recurring products, billing periods, quantities, and contract changes."],
    [38, "Renewal Management", "Create renewal opportunities and alerts from upcoming subscription expirations."],
    [39, "Order Handoff", "Convert accepted quotes into fulfillment-ready orders without re-entering information."],
    [40, "Commission Rules", "Calculate sales credit using configurable plans, thresholds, splits, and exceptions."],
  ]),
  ...group("Marketing Foundation", "crm", null, [
    [41, "Embedded Form Builder", "Create branded lead, registration, survey, and request forms without code."],
    [42, "Landing Page Builder", "Publish campaign pages with responsive layouts and conversion tracking."],
    [43, "Dynamic Audience Segments", "Build continuously updated groups from profile, behavior, and transaction data."],
    [44, "Consent and Preference Center", "Record communication permissions by channel, purpose, brand, and jurisdiction."],
    [45, "Campaign Management", "Coordinate audiences, activities, owners, schedules, assets, and expected outcomes."],
    [46, "Campaign Budget Tracking", "Compare planned and actual spending against pipeline and revenue results."],
    [47, "Source and Medium Tracking", "Preserve acquisition details from first interaction through conversion."],
    [48, "Multi-Touch Attribution", "Allocate commercial outcomes across the marketing interactions that influenced them."],
    [49, "Event and Webinar Management", "Manage registrations, attendance, follow-up, and opportunity creation."],
    [50, "Referral Program Tracking", "Attribute introductions to customers, partners, employees, or external advocates."],
  ]),
  ...group("Journeys and Engagement", "crm", null, [
    [51, "Visual Journey Builder", "Design multi-step customer journeys using triggers, conditions, delays, and actions."],
    [52, "Drip Campaigns", "Deliver sequenced communications based on timing and recipient behavior."],
    [53, "Event-Triggered Outreach", "Start engagement when records, transactions, visits, or lifecycle stages change."],
    [54, "Behavioral Nurturing", "Adjust content and follow-up based on clicks, visits, responses, and inactivity."],
    [55, "Account-Based Campaigns", "Coordinate personalized engagement across stakeholders within target organizations."],
    [56, "Experiment Management", "Compare message, audience, page, and timing variants against defined outcomes."],
    [57, "Communication Frequency Caps", "Limit contact volume across campaigns to prevent audience fatigue."],
    [58, "Suppression Rules", "Exclude unsuitable, opted-out, conflicted, or recently contacted recipients."],
    [59, "Conversion Goal Tracking", "Measure journey performance against configurable business milestones."],
    [60, "Send-Time Selection", "Schedule delivery according to recipient time zones and historical engagement patterns."],
  ]),
  ...group("Communications", "crm", null, [
    [61, "Shared Team Inbox", "Manage group email addresses with ownership, status, and response accountability."],
    [62, "Two-Way Email Synchronization", "Associate sent and received messages with the correct business records."],
    [63, "Calendar Synchronization", "Connect meetings and availability across supported calendar providers."],
    [64, "Appointment Scheduling", "Let external participants book approved time slots with suitable team members."],
    [65, "SMS Messaging", "Send, receive, template, and audit text conversations from customer records."],
    [66, "Business Messaging Channels", "Manage supported channels such as WhatsApp within governed customer threads."],
    [67, "Unified Conversation History", "Combine channel interactions into one chronological customer conversation."],
    [68, "Approved Message Templates", "Standardize recurring responses while preserving controlled personalization."],
    [69, "Reusable Content Snippets", "Insert governed product, policy, pricing, or support language quickly."],
    [70, "Call Logging and Transcription", "Capture call metadata, notes, recordings, and searchable transcripts."],
  ]),
  ...group("Customer Service", "crm", null, [
    [71, "Case Management", "Track customer issues, requests, ownership, status, priority, and resolution."],
    [72, "Omnichannel Case Intake", "Create cases from email, forms, messaging, portals, APIs, or staff entry."],
    [73, "Skill-Based Case Routing", "Assign work according to expertise, language, workload, and customer tier."],
    [74, "Service-Level Policies", "Define response and resolution commitments for different customer entitlements."],
    [75, "Escalation Management", "Elevate cases when risk, severity, inactivity, or deadlines require intervention."],
    [76, "Support Queue Workspaces", "Give teams prioritized views of pending, active, and overdue work."],
    [77, "Knowledge Base", "Publish governed solutions, policies, guides, and internal troubleshooting instructions."],
    [78, "Problem and Incident Linking", "Group related cases under a shared underlying issue or service incident."],
    [79, "Customer Entitlements", "Determine available support levels from products, contracts, plans, or exceptions."],
    [80, "Satisfaction Measurement", "Collect structured feedback after interactions and analyze service quality."],
  ]),
  ...group("Customer and Partner Portals", "crm", null, [
    [81, "White-Labeled Customer Portal", "Provide each tenant with a branded, configurable self-service environment."],
    [82, "Passwordless Secure Access", "Grant time-bound portal entry without requiring permanent user credentials."],
    [83, "Self-Service Request Submission", "Let customers initiate support, sales, service, and operational requests."],
    [84, "Portal Knowledge Search", "Surface relevant articles before customers create avoidable support cases."],
    [85, "Case Status Tracking", "Allow customers to review progress, replies, deadlines, and resolutions."],
    [86, "Secure Document Exchange", "Share sensitive files with controlled access, expiry, and download auditing."],
    [87, "External Approval Tasks", "Let customers review and approve proposals, documents, or requested actions."],
    [88, "Billing and Order Visibility", "Present permitted invoices, subscriptions, quotes, orders, and balances."],
    [89, "Delegated Organization Access", "Let customer administrators manage their own authorized portal users."],
    [90, "Portal Localization", "Adapt language, time, currency, branding, and content for each audience."],
  ]),
  ...group("Workflow and Process Management", "crm", null, [
    [91, "Visual Workflow Designer", "Build governed business processes from triggers, conditions, and actions."],
    [92, "Conditional Approval Chains", "Route approvals according to value, risk, department, or record attributes."],
    [93, "Scheduled Automations", "Run recurring operational processes at defined times and intervals."],
    [94, "Record Event Triggers", "Respond when records are created, changed, linked, closed, or deleted."],
    [95, "Business Validation Rules", "Prevent incomplete, inconsistent, or unauthorized data from progressing."],
    [96, "Automated Task Creation", "Generate accountable work items from lifecycle events and process conditions."],
    [97, "Dynamic Routing Rules", "Direct records to the right user, queue, team, or external system."],
    [98, "Timers and Deadline Controls", "Start, pause, resume, and monitor process-specific countdowns."],
    [99, "Outbound Webhook Actions", "Notify external services when governed business events occur."],
    [100, "Workflow Version Management", "Test, publish, compare, and restore process definitions safely."],
  ]),
  ...group("Documents and Contracts", "crm", null, [
    [101, "Document Template Builder", "Generate consistent documents using approved layouts and live business data."],
    [102, "Merge-Field Library", "Insert governed CRM, transaction, contact, and tenant values into documents."],
    [103, "Electronic Signature Integration", "Send agreements for signing and retain complete execution evidence."],
    [104, "Document Version Control", "Preserve revisions, authorship, timestamps, and superseded copies."],
    [105, "Clause Library", "Maintain approved contractual language by jurisdiction, product, risk, or use case."],
    [106, "Contract Approval Routing", "Send agreements through legal, finance, sales, and executive review."],
    [107, "Redline Tracking", "Compare proposed contractual edits and record negotiation decisions."],
    [108, "Obligation and Expiry Alerts", "Notify owners about renewals, notice periods, milestones, and commitments."],
    [109, "Cryptographic File Verification", "Detect document alteration using stored hashes and immutable evidence."],
    [110, "Document Retention Policies", "Govern storage, archival, deletion, and legal holds by document class."],
  ]),
  ...group("Collaboration and Productivity", "crm", null, [
    [111, "Shared Record Notes", "Keep contextual team notes attached to customers, deals, cases, and projects."],
    [112, "Mentions and Notifications", "Bring colleagues into discussions with direct, traceable references."],
    [113, "Team Activity Feeds", "Show relevant changes and actions across selected records and workspaces."],
    [114, "Role-Based Workspaces", "Give each function focused navigation, data, actions, and performance views."],
    [115, "Task Management", "Assign work with owners, priorities, dependencies, due dates, and completion evidence."],
    [116, "Collaborative Project Boards", "Coordinate implementation, onboarding, delivery, and internal initiatives."],
    [117, "Meeting Workspaces", "Prepare agendas, attendees, notes, decisions, actions, and follow-up."],
    [118, "Contextual File Attachments", "Associate supporting files with records while retaining access controls."],
    [119, "Decision Logs", "Preserve significant choices, participants, reasoning, and effective dates."],
    [120, "Structured Team Handoffs", "Transfer ownership with required context, open obligations, and acceptance."],
  ]),
  ...group("Reporting and Analytics", "crm", null, [
    [121, "Configurable Dashboard Builder", "Assemble role-specific metrics, charts, tables, and operational queues."],
    [122, "Self-Service Report Builder", "Create filtered reports without requiring database or engineering access."],
    [123, "Cross-Object Reporting", "Analyze relationships across customers, activities, deals, cases, and transactions."],
    [124, "Funnel Analysis", "Measure movement, conversion, delay, and leakage between lifecycle stages."],
    [125, "Cohort Analysis", "Compare customer groups by acquisition period, segment, behavior, or product."],
    [126, "Forecast Accuracy Analysis", "Compare submitted forecasts with actual outcomes by team and period."],
    [127, "Service Operations Analytics", "Monitor volumes, backlogs, response times, resolutions, and escalations."],
    [128, "Marketing Return Analysis", "Relate campaign investment to engagement, pipeline, and recognized revenue."],
    [129, "Threshold and Anomaly Alerts", "Notify owners when metrics exceed limits or depart from normal patterns."],
    [130, "Scheduled Report Distribution", "Deliver governed reports to approved recipients on recurring schedules."],
  ]),
  ...group("Security, Governance, and Data Control", "crm", null, [
    [131, "Row-Level Tenant Isolation", "Enforce separation of every tenant's records at the database layer."],
    [132, "Role-Based Access Control", "Assign permissions through reusable organizational and functional roles."],
    [133, "Field-Level Security", "Restrict sensitive values independently from access to the parent record."],
    [134, "Team and Territory Sharing", "Extend controlled access through ownership, hierarchy, and membership rules."],
    [135, "Enterprise Single Sign-On", "Authenticate users through tenant-approved identity providers."],
    [136, "Automated User Provisioning", "Synchronize user creation, updates, and deactivation through directory services."],
    [137, "Immutable Audit Logs", "Record security, configuration, access, and business-data changes."],
    [138, "Data Retention Automation", "Apply configurable archival and deletion schedules to eligible records."],
    [139, "Regional Data Residency", "Keep tenant data within approved geographic storage boundaries."],
    [140, "Privacy Request Management", "Govern subject access, correction, portability, restriction, and deletion workflows."],
  ]),
  ...group("Assisted Intelligence and Automation", "crm", null, [
    [141, "Record Summaries", "Condense long histories into factual, source-linked operational briefings."],
    [142, "Conversation Summaries", "Extract decisions, commitments, questions, and next steps from communications."],
    [143, "Response Drafting", "Prepare editable customer messages using approved context and tone."],
    [144, "Request Classification", "Categorize incoming leads, cases, documents, and messages for accurate routing."],
    [145, "Sentiment Indicators", "Flag material changes in customer tone for human review."],
    [146, "Deal Risk Assessment", "Identify missing stakeholders, inactivity, slippage, and unresolved dependencies."],
    [147, "Data Quality Suggestions", "Recommend corrections for incomplete, inconsistent, or likely duplicate records."],
    [148, "Natural-Language Reporting", "Translate business questions into permission-aware reports and filters."],
    [149, "Knowledge-Grounded Assistant", "Answer staff questions using approved tenant documents and records."],
    [150, "Human Approval Gates", "Require review before assisted actions communicate, commit, or alter critical data."],
  ]),
  ...group("Extensibility and Tenant Configuration", "crm", null, [
    [151, "Tenant-Specific Modules", "Enable only the business capabilities purchased or required by each tenant."],
    [152, "Page Layout Builder", "Configure record screens, sections, tabs, and actions by role or record type."],
    [153, "Formula Field Engine", "Calculate derived values from related records and configurable expressions."],
    [154, "Custom Validation Designer", "Define tenant-specific quality and compliance requirements without code."],
    [155, "Versioned Application API", "Provide stable programmatic access with explicit authentication and permissions."],
    [156, "Business Event Stream", "Publish governed record events for downstream systems and integrations."],
    [157, "Integration Connector Framework", "Standardize authentication, mapping, synchronization, and error handling."],
    [158, "Isolated Sandbox Tenants", "Test configuration, integrations, and workflows without affecting production."],
    [159, "Configuration Package Deployment", "Promote approved customizations between environments with dependency checks."],
    [160, "Per-Tenant Feature Flags", "Release, restrict, or trial capabilities independently for selected customers."],
  ]),
  ...group("Global and Mobile Operations", "crm", null, [
    [161, "Responsive Mobile Workspace", "Provide full operational access across phones, tablets, and desktops."],
    [162, "Offline Mobile Records", "Capture approved data without connectivity and synchronize it safely later."],
    [163, "Location-Aware Field Visits", "Record check-ins, service locations, travel, and visit outcomes."],
    [164, "Barcode and QR Capture", "Retrieve or update records by scanning physical assets and documents."],
    [165, "Multi-Currency Operations", "Store transaction currency, conversion rates, and reporting currency accurately."],
    [166, "Multilingual Interface", "Localize navigation, labels, messages, templates, and portal experiences."],
    [167, "Time-Zone-Aware Scheduling", "Present meetings, deadlines, and automations in each user's local time."],
    [168, "Regional Tax Configuration", "Apply jurisdiction-specific tax structures to quotes and transactions."],
    [169, "Accessibility Controls", "Support keyboard navigation, screen readers, contrast, scaling, and reduced motion."],
    [170, "Omnichannel Notification Preferences", "Let users govern which alerts reach each device and channel."],
  ]),
  ...group("Finance and Accounting", "erp", null, [
    [171, "Multi-Entity General Ledger", "Maintain separate books while consolidating group-wide financials."],
    [172, "Configurable Chart of Accounts", "Define account structures by tenant, entity, region, or industry."],
    [173, "Real-Time Journal Engine", "Post balanced journal entries immediately from operational transactions."],
    [174, "Automated Posting Rules", "Convert business events into consistent accounting entries without manual work."],
    [175, "Double-Entry Enforcement", "Reject incomplete or unbalanced postings at the database level."],
    [176, "Fiscal Calendar Management", "Support custom periods, adjustment periods, and non-calendar fiscal years."],
    [177, "Period-Close Orchestration", "Coordinate reconciliations, approvals, dependencies, and close checklists."],
    [178, "Intercompany Accounting", "Generate reciprocal entries between related entities automatically."],
    [179, "Consolidation and Eliminations", "Combine entities while removing intercompany balances and transactions."],
    [180, "Multicurrency Accounting", "Record transactions and reports in functional, local, and presentation currencies."],
    [181, "Foreign-Exchange Revaluation", "Revalue open balances using governed exchange-rate sources."],
    [182, "Bank Feed Aggregation", "Import transactions securely from multiple banks and financial accounts."],
    [183, "Intelligent Bank Reconciliation", "Match bank activity against ledger entries and surface exceptions."],
    [184, "Cash-Position Forecasting", "Project liquidity across accounts, currencies, and legal entities."],
    [185, "Treasury Control Center", "Govern transfers, signatories, limits, and cash concentration."],
    [186, "Vendor Invoice Capture", "Extract, validate, classify, and route supplier invoices for approval."],
    [187, "Receivables Aging", "Track outstanding balances by entity, currency, and aging bucket."],
    [188, "Remittance Allocation", "Match incoming payments to invoices, installments, and unapplied balances."],
    [189, "Credit and Debit Adjustments", "Issue governed corrections with complete approval histories."],
    [190, "Enterprise Tax Engine", "Calculate jurisdiction-specific taxes across products, services, and entities."],
    [191, "Withholding-Tax Management", "Apply, document, and report statutory deductions automatically."],
    [192, "Cost-Center Accounting", "Attribute income and expenditure to departments, locations, or operating units."],
    [193, "Allocation Engine", "Distribute shared costs using configurable statistical or operational drivers."],
    [194, "Budgeting and Forecasting", "Create rolling forecasts, scenarios, and budget-versus-actual comparisons."],
    [195, "Financial Statement Builder", "Produce governed balance sheets, income statements, and cash-flow reports."],
  ]),
  ...group("Billing, Subscriptions, and Revenue", "erp", null, [
    [196, "Usage Metering", "Capture billable events from products, APIs, storage, seats, or transactions."],
    [197, "Recurring Subscription Billing", "Automate scheduled charges across monthly, annual, and custom terms."],
    [198, "Product and Plan Catalog", "Manage commercial packages, add-ons, currencies, and effective dates."],
    [199, "Billing Entitlements", "Link paid plans to enforceable product access and consumption limits."],
    [200, "Tiered Pricing Engine", "Support volume, graduated, flat-rate, and threshold-based pricing."],
    [201, "Contract Billing Schedules", "Generate invoices from milestones, retainers, installments, or service periods."],
    [202, "Automated Proration", "Calculate fair mid-cycle upgrades, downgrades, additions, and cancellations."],
    [203, "Consolidated Invoicing", "Combine charges across departments, locations, or subsidiaries into governed invoices."],
    [204, "Collections and Dunning", "Run escalating reminders, retries, holds, and collection workflows."],
    [205, "Payment Gateway Orchestration", "Route payments across providers, currencies, and regional methods."],
    [206, "Revenue Recognition", "Recognize revenue according to delivery obligations and accounting schedules."],
    [207, "Deferred-Revenue Accounting", "Track billed but unearned revenue and automate periodic releases."],
    [208, "Billing Dispute Management", "Isolate disputed charges while preserving the undisputed collection process."],
    [209, "Hierarchical Account Billing", "Bill parent organizations centrally while retaining subsidiary-level detail."],
    [210, "Compliant Electronic Invoicing", "Generate, transmit, and archive jurisdiction-approved invoice formats."],
  ]),
  ...group("Procurement and Supplier Operations", "erp", null, [
    [211, "Supplier Master Registry", "Maintain governed supplier identities, banking data, certifications, and ownership."],
    [212, "Purchase Requisitions", "Standardize internal purchasing requests before financial commitments are made."],
    [213, "Procurement Approval Routing", "Route purchases by amount, category, entity, and risk level."],
    [214, "Request-for-Quotation Workflows", "Invite structured supplier quotations within controlled bidding windows."],
    [215, "Bid Comparison Matrix", "Compare pricing, terms, delivery, risk, and total landed cost."],
    [216, "Guided Buying Catalogs", "Direct employees toward approved products, services, and suppliers."],
    [217, "Purchase-Order Management", "Create, approve, issue, amend, and close formal purchase orders."],
    [218, "Blanket Purchase Agreements", "Govern recurring purchasing through limits, schedules, and negotiated terms."],
    [219, "Supplier Contract Calendar", "Track obligations, renewals, price reviews, and expiry dates."],
    [220, "Three-Way Matching", "Match purchase orders, receipts, and invoices before payment approval."],
    [221, "Policy-Based Spend Controls", "Block or escalate purchases that violate budgets or sourcing policies."],
    [222, "Supplier Risk Scoring", "Assess financial, operational, geographic, and compliance exposure."],
    [223, "Supplier Onboarding Portal", "Collect documentation and approvals without exposing internal systems."],
    [224, "Supplier Performance Scorecards", "Measure delivery, quality, responsiveness, and contractual compliance."],
    [225, "Procurement Savings Analytics", "Quantify negotiated, realized, avoided, and leakage-related savings."],
  ]),
  ...group("Inventory and Warehousing", "erp", null, [
    [226, "Universal Item Catalog", "Manage products, materials, consumables, and services under governed classifications."],
    [227, "Multi-Warehouse Inventory", "Track stock independently across facilities, entities, and tenants."],
    [228, "Bin and Location Control", "Model aisles, zones, shelves, staging areas, and restricted locations."],
    [229, "Lot and Batch Tracking", "Trace inventory by production or procurement batch."],
    [230, "Serial-Number Tracking", "Follow individually identifiable units throughout their lifecycle."],
    [231, "Expiry and Shelf-Life Control", "Prioritize stock usage and prevent expired-item fulfillment."],
    [232, "Inventory Reservations", "Commit stock to authorized demand without prematurely reducing availability."],
    [233, "Cycle-Counting Programs", "Schedule targeted counts by value, risk, or movement frequency."],
    [234, "Physical Inventory Management", "Freeze, count, reconcile, approve, and post full stocktakes."],
    [235, "Reorder-Point Automation", "Trigger replenishment when projected stock crosses configurable thresholds."],
    [236, "Inter-Warehouse Transfers", "Govern picks, shipments, receipts, and in-transit inventory."],
    [237, "Unit-of-Measure Conversion", "Buy, store, consume, and sell inventory in different measurement units."],
    [238, "Inventory Costing Methods", "Support FIFO, weighted-average, standard, and specific-cost models."],
    [239, "Inventory Valuation Snapshots", "Reconstruct stock value accurately at any reporting date."],
    [240, "Kit and Bundle Management", "Assemble or disassemble grouped items while preserving component traceability."],
  ]),
  ...group("Supply Chain and Logistics", "erp", null, [
    [241, "Demand Forecasting", "Predict future requirements from seasonality, history, and operational drivers."],
    [242, "Supply Planning", "Balance projected demand against inventory, production, and purchasing capacity."],
    [243, "Distribution Requirements Planning", "Calculate replenishment needs across multi-level distribution networks."],
    [244, "Safety-Stock Optimization", "Set buffers dynamically according to volatility and service targets."],
    [245, "Available-to-Promise Calculation", "Provide reliable fulfillment dates using current and projected supply."],
    [246, "Automated Replenishment", "Generate planned transfers or purchase requests from approved policies."],
    [247, "Supplier Lead-Time Modeling", "Maintain expected, variable, and actual lead times by item and route."],
    [248, "Shipment Planning", "Consolidate orders into cost-effective, capacity-aware shipments."],
    [249, "Carrier Rate Shopping", "Compare contracted transportation rates and service levels automatically."],
    [250, "Logistics Route Optimization", "Sequence deliveries according to distance, capacity, windows, and constraints."],
    [251, "Freight Audit and Settlement", "Validate carrier charges against contracts, weights, lanes, and accessorials."],
    [252, "End-to-End Track and Trace", "Monitor goods from origin through every handoff and destination."],
    [253, "Customs Documentation", "Generate trade declarations, classifications, origin records, and shipping documents."],
    [254, "Reverse Logistics", "Govern returns, inspections, repairs, restocking, and disposal."],
    [255, "Supply-Chain Control Tower", "Surface delays, shortages, exceptions, and network-wide operational risk."],
  ]),
  ...group("Projects and Professional Services", "erp", null, [
    [256, "Project Template Library", "Standardize repeatable project structures, controls, and deliverables."],
    [257, "Work-Breakdown Structures", "Decompose complex programs into governed phases, tasks, and work packages."],
    [258, "Resource Capacity Planning", "Match planned work against team availability and capability."],
    [259, "Project Time Capture", "Record billable and non-billable effort against authorized activities."],
    [260, "Project Expense Allocation", "Attribute travel, materials, services, and overhead to project work."],
    [261, "Project Budget Control", "Set baselines and enforce limits by phase, task, or cost category."],
    [262, "Project Cost Accounting", "Calculate committed, incurred, accrued, and forecast completion costs."],
    [263, "Earned-Value Management", "Measure schedule and cost performance against approved baselines."],
    [264, "Milestone Billing", "Trigger invoices only when defined project outcomes are approved."],
    [265, "Project Procurement", "Link requisitions, commitments, receipts, and supplier costs to projects."],
    [266, "Project Inventory", "Reserve, issue, return, and reconcile materials against project work."],
    [267, "Dependency Scheduling", "Model prerequisites, critical paths, constraints, and schedule impacts."],
    [268, "Change-Order Governance", "Price, approve, version, and audit changes to project scope."],
    [269, "Portfolio Capacity Planning", "Balance investment priorities against shared resources and constraints."],
    [270, "Project Profitability Analysis", "Compare revenue, cost, utilization, and margin at every project level."],
  ]),
  ...group("Workforce and Payroll", "erp", null, [
    [271, "Organizational Hierarchy", "Model entities, divisions, departments, teams, and reporting structures."],
    [272, "Governed Employee Records", "Centralize employment, identity, payroll, and statutory information securely."],
    [273, "Position Management", "Control approved roles independently from individual employees."],
    [274, "Headcount Planning", "Forecast vacancies, hiring needs, costs, and workforce scenarios."],
    [275, "Workforce Scheduling", "Build coverage-aware schedules across locations, teams, and operating hours."],
    [276, "Time and Attendance", "Capture working time, breaks, exceptions, and approvals."],
    [277, "Shift Rules Engine", "Enforce overtime, rest periods, premiums, rotations, and labor constraints."],
    [278, "Leave Management", "Calculate entitlements and route absence requests according to policy."],
    [279, "Payroll Processing", "Calculate earnings, deductions, reimbursements, taxes, and net pay."],
    [280, "Multicountry Payroll Rules", "Configure statutory calculations and reporting by jurisdiction."],
    [281, "Compensation Band Management", "Govern salary ranges, grades, allowances, and review cycles."],
    [282, "Benefits Administration", "Manage eligibility, enrollment, contributions, and benefit-provider files."],
    [283, "Skills and Certification Registry", "Track workforce capabilities, qualifications, and renewal requirements."],
    [284, "Contractor Workforce Control", "Govern engagements, timesheets, rates, access dates, and compliance documents."],
    [285, "Labor Cost Allocation", "Distribute payroll costs across projects, departments, sites, and entities."],
  ]),
  ...group("Assets and Maintenance", "erp", null, [
    [286, "Enterprise Asset Register", "Maintain a complete record of owned, leased, and controlled assets."],
    [287, "Automated Depreciation", "Calculate book and tax depreciation across multiple schedules."],
    [288, "Asset Capitalization Workflow", "Convert qualifying expenditure into controlled fixed assets."],
    [289, "Asset Lifecycle Tracking", "Follow acquisition, deployment, transfer, maintenance, and retirement."],
    [290, "Location and Custody Tracking", "Record where assets are and who is accountable for them."],
    [291, "Preventive Maintenance Plans", "Schedule recurring service by time, usage, or regulatory interval."],
    [292, "Predictive Maintenance Alerts", "Identify likely failures from condition and performance signals."],
    [293, "Maintenance Work Orders", "Plan labor, parts, procedures, downtime, and approvals."],
    [294, "Spare-Parts Planning", "Reserve and replenish critical maintenance components."],
    [295, "Meter and Usage Readings", "Capture hours, mileage, cycles, consumption, or production output."],
    [296, "Warranty Management", "Track coverage, claims, supplier responsibility, and expiration."],
    [297, "Asset Inspection Programs", "Standardize inspections, evidence capture, defects, and corrective actions."],
    [298, "Asset Disposal and Retirement", "Govern sale, write-off, recycling, data removal, and ledger treatment."],
  ]),
  ...group("Field Service Operations", "erp", null, [
    [299, "Real-Time Dispatch Board", "Coordinate field assignments, urgency, location, and technician availability."],
    [300, "Technician Mobile Workspace", "Provide schedules, instructions, records, and updates on mobile devices."],
    [301, "Skills-Based Assignment", "Match work to qualified personnel by certification, territory, and availability."],
    [302, "Offline Work Packs", "Keep critical job information usable without network connectivity."],
    [303, "Digital Service Checklists", "Enforce consistent procedures and required evidence at the worksite."],
    [304, "Proof of Service", "Capture signatures, timestamps, photos, and geolocation for completed work."],
    [305, "Field Parts Consumption", "Record materials used and reconcile technician-held inventory."],
    [306, "Service-Level Clocks", "Track response and resolution obligations in real time."],
    [307, "Emergency Escalation Rules", "Reassign or escalate critical work when operational thresholds are breached."],
    [308, "Site Access and Safety Briefs", "Present location-specific permissions, hazards, and entry procedures."],
    [309, "Equipment Diagnostic Capture", "Record readings, fault codes, tests, and technician findings."],
    [310, "Field Expense and Per-Diem Claims", "Capture travel and job expenses against governed policies."],
  ]),
  ...group("Manufacturing and Quality", "erp", null, [
    [311, "Bill-of-Materials Management", "Define versioned component structures for manufactured products."],
    [312, "Production Routing", "Specify operations, sequence, labor, equipment, and standard times."],
    [313, "Work-Center Management", "Model productive capacity, calendars, rates, and constraints."],
    [314, "Finite-Capacity Scheduling", "Build executable production schedules around real resource limits."],
    [315, "Shop-Floor Execution", "Dispatch work and capture progress directly from production areas."],
    [316, "Production Orders", "Authorize quantities, materials, operations, dates, and responsible facilities."],
    [317, "Material Issue and Backflush", "Record component consumption manually or from completed output."],
    [318, "Work-in-Progress Tracking", "Value and trace partially completed production at every stage."],
    [319, "Overall Equipment Effectiveness", "Measure availability, performance, and quality losses."],
    [320, "Recipe and Formula Control", "Govern scalable formulations, yields, tolerances, and substitutions."],
    [321, "Engineering Change Control", "Review and approve changes to designs, materials, and processes."],
    [322, "Quality Planning", "Define inspection points, specifications, sampling methods, and acceptance criteria."],
    [323, "Nonconformance Management", "Quarantine defects and document disposition decisions."],
    [324, "Corrective and Preventive Actions", "Investigate root causes and verify remediation effectiveness."],
    [325, "Product Genealogy", "Trace finished goods through every material, batch, process, and inspection."],
  ]),
  ...group("Compliance, Security, and Platform Administration", "erp", null, [
    [326, "Automated Tenant Provisioning", "Create isolated environments, defaults, policies, and resources consistently."],
    [327, "Custom Domain and Subdomain Routing", "Map branded tenant addresses securely at the edge."],
    [328, "Entitlement Drift Detection", "Compare contracted access with live modules, quotas, and exceptions."],
    [329, "Data Sovereignty Policy Validation", "Block deployment choices or integrations that violate residency rules."],
    [330, "Tenant-Managed Encryption Keys", "Allow regulated customers to control key rotation and revocation."],
    [331, "Permission Simulation", "Preview a user's effective access before publishing role or sharing changes."],
    [332, "Identity Provider Health Monitoring", "Test federation metadata, certificates, and provisioning before failures occur."],
    [333, "Segregation-of-Duties Engine", "Detect and prevent conflicting permissions and transactions."],
    [334, "Audit Integrity Anchoring", "Periodically seal audit batches with independently verifiable hashes."],
    [335, "Legal-Hold Conflict Resolution", "Stop scheduled deletion when preservation duties override retention rules."],
    [336, "Privacy Data Discovery Map", "Locate personal data across objects, files, and integrations before responding."],
    [337, "Scoped Support Access", "Grant time-bound, approved, and fully audited administrative assistance."],
    [338, "Tenant-Level Backup and Recovery", "Restore isolated customer data without affecting other tenants."],
    [339, "Compliance Evidence Center", "Map controls, tests, owners, exceptions, and proof to regulatory frameworks."],
    [340, "Tenant Operations Console", "Monitor health, usage, quotas, jobs, incidents, suspension, and offboarding."],
  ]),
  ...group("Real Estate Pack", "pack", "Real Estate", [
    [341, "Parcel-to-Portfolio Graph", "Connect land parcels, buildings, units, owners, and tenants."],
    [342, "Live Unit Availability", "Show real-time vacancy, holds, bookings, and sales status."],
    [343, "Development Phase Tracker", "Monitor approvals, construction stages, launches, and handovers."],
    [344, "Lease Abstraction Engine", "Convert key lease terms into searchable structured records."],
    [345, "Rent Escalation Scheduler", "Automate contractual increases, notices, and revised invoices."],
    [346, "Broker Commission Manager", "Calculate splits, milestones, clawbacks, and payouts."],
    [347, "Site Visit Coordinator", "Schedule tours, assign agents, and capture buyer feedback."],
    [348, "Offer Comparison Workspace", "Compare pricing, concessions, contingencies, and buyer strength."],
    [349, "Title Due-Diligence Checklist", "Track ownership evidence, encumbrances, searches, and approvals."],
    [350, "Handover and Snagging Portal", "Document defects, remedies, acceptance, and possession."],
  ]),
  ...group("Legal Pack", "pack", "Legal", [
    [351, "Conflict Check Engine", "Screen prospective matters against clients, entities, and adversaries."],
    [352, "Court Deadline Docketing", "Calculate, assign, and escalate jurisdiction-specific filing dates."],
    [353, "Jurisdictional Precedent Recommender", "Surface approved prior language using matter, venue, and risk context."],
    [354, "Negotiation Issue Matrix", "Track open contract positions, owners, fallbacks, and resolution status."],
    [355, "Signature Authority Matrix", "Route agreements according to value, entity, and signing limits."],
    [356, "Litigation Hold Manager", "Preserve relevant records and document custodian acknowledgements."],
    [357, "Client Trust Accounting", "Separate client funds with matter-level reconciliation controls."],
    [358, "Matter Billing Rules", "Apply retainers, rates, caps, write-offs, and alternative fees."],
    [359, "Corporate Entity Register", "Track directors, ownership, filings, resolutions, and renewals."],
    [360, "Outside Counsel Scorecards", "Compare firms by outcomes, responsiveness, diversity, and spend."],
  ]),
  ...group("Healthcare Pack", "pack", "Healthcare", [
    [361, "Referral Journey Manager", "Track referrals from receipt through consultation and closure."],
    [362, "Care Pathway Orchestrator", "Coordinate multidisciplinary tasks around defined treatment pathways."],
    [363, "Appointment Waitlist Optimizer", "Fill cancellations using urgency and availability rules."],
    [364, "Consent and Directive Vault", "Preserve signed permissions, directives, and revocation history."],
    [365, "Practitioner Credentialing", "Monitor licenses, certifications, privileges, and expiry dates."],
    [366, "Prior Authorization Tracker", "Manage payer requirements, submissions, evidence, and decisions."],
    [367, "Patient Case Conference", "Unite clinicians around notes, actions, and accountable follow-ups."],
    [368, "Clinical Access Segmentation", "Restrict sensitive records by role, facility, and relationship."],
    [369, "Claims Denial Workbench", "Categorize denials, coordinate appeals, and identify recurring causes."],
    [370, "Preventive Outreach Campaigns", "Trigger screenings and reminders by care-gap criteria."],
  ]),
  ...group("Education Pack", "pack", "Education", [
    [371, "Admissions Pipeline", "Manage inquiries, applications, interviews, offers, and enrollment."],
    [372, "Unified Student Record", "Consolidate academic, financial, support, and engagement history."],
    [373, "Course Capacity Planner", "Balance demand, prerequisites, room limits, and instructor availability."],
    [374, "Attendance Risk Alerts", "Identify persistent absence and initiate intervention workflows."],
    [375, "Alumni Relationship Hub", "Track engagement, mentoring, events, giving, and career milestones."],
    [376, "Faculty Workload Planner", "Allocate teaching, research, supervision, and administrative duties."],
    [377, "Guardian Communication Center", "Deliver localized updates with consent and delivery tracking."],
    [378, "Scholarship Administration", "Score eligibility, manage awards, and monitor funding conditions."],
    [379, "Placement and Internship Pipeline", "Connect students, employers, applications, and outcomes."],
    [380, "Accommodation Plan Manager", "Coordinate approved learning support while protecting confidentiality."],
  ]),
  ...group("Hospitality Pack", "pack", "Hospitality", [
    [381, "Unified Guest Profile", "Combine preferences, stays, requests, spending, and service recovery."],
    [382, "Reservation Journey Board", "Track inquiry, booking, modification, arrival, and departure."],
    [383, "Dynamic Room Inventory", "Control availability across properties, channels, and room classes."],
    [384, "Group Block Manager", "Coordinate room allotments, release dates, attendees, and billing."],
    [385, "Personalized Upsell Engine", "Recommend upgrades, dining, transport, and experiences before arrival."],
    [386, "Housekeeping Turnover Board", "Prioritize room cleaning using departure and arrival timing."],
    [387, "Property Maintenance Dispatch", "Route guest-reported issues with room and urgency context."],
    [388, "Loyalty Tier Manager", "Operate points, benefits, status progression, and partner rewards."],
    [389, "Banquet Event Workspace", "Manage function sheets, menus, seating, vendors, and charges."],
    [390, "Reputation Recovery Desk", "Convert reviews and complaints into accountable resolution cases."],
  ]),
  ...group("Retail and Ecommerce Pack", "pack", "Retail and Ecommerce", [
    [391, "Omnichannel Product Catalog", "Govern product information across stores, sites, and marketplaces."],
    [392, "Distributed Stock View", "Expose inventory by location, channel, reservation, and transit status."],
    [393, "Merchandise Affinity Graph", "Reveal products and categories commonly browsed, bought, or returned together."],
    [394, "Cart Recovery Journeys", "Trigger personalized reminders without over-contacting prospects."],
    [395, "Returns and Exchange Desk", "Coordinate eligibility, shipping, inspection, refund, and restocking."],
    [396, "Loyalty Wallet", "Manage points, credits, vouchers, tiers, and expiration rules."],
    [397, "Promotion Guardrails", "Prevent invalid discount stacking, margin erosion, and channel conflicts."],
    [398, "Store Clienteling App", "Give associates customer context, wish lists, and follow-up tasks."],
    [399, "Marketplace Order Router", "Normalize and route orders from multiple external marketplaces."],
    [400, "Subscription Commerce Manager", "Handle renewals, skips, bundles, churn signals, and recovery."],
  ]),
  ...group("Construction Pack", "pack", "Construction", [
    [401, "Tender and Bid Room", "Control invitations, bidder questions, submissions, and comparisons."],
    [402, "Bill of Quantities Manager", "Track planned, committed, completed, and certified quantities."],
    [403, "Subcontractor Prequalification", "Assess licenses, safety, capacity, insurance, and financial strength."],
    [404, "Digital Site Diary", "Record labor, weather, deliveries, equipment, progress, and disruptions."],
    [405, "Request for Information Workflow", "Route technical questions and measure response impact."],
    [406, "Submittal Register", "Control drawings, samples, approvals, revisions, and lead times."],
    [407, "Delay and Extension Claims", "Quantify disruption events, notices, responsibility, and time entitlement."],
    [408, "Critical Path Monitor", "Surface delays and downstream dependencies across project schedules."],
    [409, "Safety Incident Command", "Capture events, investigations, corrective actions, and recurrence trends."],
    [410, "Punch List Closeout", "Assign defects, verify remediation, and compile completion evidence."],
  ]),
  ...group("Professional Services Pack", "pack", "Professional Services", [
    [411, "Skills-Based Resource Planner", "Match specialists to engagements by capability and availability."],
    [412, "Statement of Work Builder", "Assemble scope, milestones, assumptions, pricing, and acceptance terms."],
    [413, "Rate Card Governance", "Manage client, role, location, and effective-dated billing rates."],
    [414, "Utilization Forecaster", "Project bench time, overload, and hiring needs."],
    [415, "Engagement Margin Monitor", "Compare revenue, labor, expenses, and write-offs in real time."],
    [416, "Retainer Consumption Tracker", "Show usage, remaining value, replenishment, and rollover conditions."],
    [417, "Expertise Directory", "Locate internal specialists by experience, credentials, and project history."],
    [418, "Client Health Index", "Combine delivery, financial, sentiment, and relationship signals."],
    [419, "Deliverable Approval Room", "Centralize review cycles, feedback, acceptance, and evidence."],
  ]),
  ...group("Nonprofit Pack", "pack", "Nonprofit", [
    [420, "Constituent Giving Capacity Profile", "Combine giving history, affiliations, interests, and prospect research signals."],
    [421, "Gift Processing Ledger", "Record donations, pledges, matching gifts, receipts, and adjustments."],
    [422, "Grant Lifecycle Manager", "Track opportunities, applications, reporting duties, and renewals."],
    [423, "Volunteer Coordination Hub", "Match skills and availability to shifts and programs."],
    [424, "Fundraising Campaign Studio", "Manage appeals, events, peer fundraisers, goals, and attribution."],
    [425, "Recurring Donor Retention", "Detect failed payments and trigger considerate recovery journeys."],
    [426, "Restricted Fund Controls", "Ensure donations are allocated and spent according to purpose."],
    [427, "Impact Evidence Register", "Link funded activities to outputs, outcomes, and supporting records."],
    [428, "Beneficiary Privacy Manager", "Separate sensitive program records using consent-based access."],
  ]),
  ...group("Logistics Pack", "pack", "Logistics", [
    [429, "Customer Shipment Promise Board", "Compare committed delivery dates with the latest operational estimate."],
    [430, "Carrier Contract Matrix", "Compare lanes, rates, surcharges, capacity, and service obligations."],
    [431, "Last-Mile Territory Designer", "Model service zones using demand, depot, travel, and coverage constraints."],
    [432, "Dock Appointment Scheduler", "Coordinate carriers, bays, labor, and loading windows."],
    [433, "Proof of Delivery Vault", "Store signatures, images, geolocation, and delivery timestamps."],
    [434, "Cold-Chain Monitor", "Alert teams to temperature excursions and compromised consignments."],
    [435, "Detention and Demurrage Control", "Track free time, charge exposure, disputes, and accountable delays."],
    [436, "Trade Compliance Screening", "Check parties, goods, destinations, and restrictions before shipment release."],
    [437, "Predictive Exception Desk", "Prioritize delayed shipments by customer and commercial impact."],
  ]),
  ...group("Manufacturing Pack", "pack", "Manufacturing", [
    [438, "Engineering Configuration Matrix", "Map selectable product variants, dependencies, exclusions, and approved combinations."],
    [439, "Material Requirements Planner", "Translate demand into purchasing and production requirements."],
    [440, "Production Sequencing Board", "Schedule work orders around capacity, tooling, and dependencies."],
    [441, "Andon Exception Board", "Signal stoppages, summon support, and measure production response time."],
    [442, "Statistical Quality Control", "Detect process variation before it becomes widespread defect."],
    [443, "Maintenance Shutdown Planner", "Coordinate plant outages, labor, permits, parts, and restart readiness."],
    [444, "Recall Containment Navigator", "Identify affected units, customers, stock, suppliers, and corrective actions."],
    [445, "Supplier Quality Cases", "Manage nonconformance, containment, corrective action, and verification."],
    [446, "Warranty Failure Analytics", "Connect returns to batches, components, factories, and causes."],
  ]),
  ...group("Finance and Insurance Pack", "pack", "Finance and Insurance", [
    [447, "Know-Your-Customer Workspace", "Collect identity, ownership, verification, and refresh evidence."],
    [448, "Transaction Risk Alerts", "Investigate suspicious patterns with explainable case histories."],
    [449, "Policy Lifecycle Manager", "Coordinate quotation, binding, endorsements, renewals, and cancellation."],
    [450, "Underwriting Decision Room", "Combine evidence, risk factors, referrals, and approval authority."],
    [451, "First-Notice-of-Loss Intake", "Capture incidents quickly and launch appropriate claim workflows."],
    [452, "Lending Pipeline", "Manage applications, documentation, underwriting, approval, and disbursement."],
    [453, "Covenant Compliance Monitor", "Track borrower obligations, ratios, evidence, and breaches."],
    [454, "Suitability and Advice Record", "Preserve recommendations, disclosures, rationale, and client acceptance."],
    [455, "Producer Commission Engine", "Calculate agent earnings, overrides, vesting, and clawbacks."],
  ]),
  ...group("Automotive Pack", "pack", "Automotive", [
    [456, "VIN-Level Inventory", "Track every vehicle's specification, location, status, and aging."],
    [457, "Dealer Lead Distribution", "Route inquiries by territory, stock, capacity, and performance."],
    [458, "Test-Drive Scheduler", "Coordinate customers, vehicles, staff, licenses, and follow-up."],
    [459, "Deal Jacket Workspace", "Assemble quotes, trade-ins, financing, approvals, and contracts."],
    [460, "Service Booking Lane", "Schedule workshop visits by technician, bay, and job duration."],
    [461, "Digital Repair Order", "Track diagnosis, authorization, labor, parts, and completion."],
    [462, "Parts Availability Network", "Locate stock across branches, warehouses, and suppliers."],
    [463, "Vehicle Warranty Claims", "Validate coverage and manage manufacturer reimbursement evidence."],
    [464, "Fleet Maintenance Console", "Monitor service intervals, downtime, costs, and replacement timing."],
  ]),
  ...group("Media Pack", "pack", "Media", [
    [465, "Editorial Calendar", "Coordinate ideas, assignments, deadlines, channels, and publication status."],
    [466, "Rights and Territory Manager", "Control usage periods, regions, formats, and exclusivity."],
    [467, "Advertising Inventory Planner", "Forecast and reserve placements across properties and dates."],
    [468, "Campaign Trafficking Desk", "Manage creatives, specifications, approvals, launches, and delivery."],
    [469, "Subscriber Relationship Hub", "Track plans, preferences, engagement, churn risk, and service cases."],
    [470, "Talent and Contributor Roster", "Manage availability, contracts, credits, rates, and releases."],
    [471, "Production Budget Control", "Track estimates, commitments, actuals, and approvals by production."],
    [472, "Creative Review Portal", "Centralize annotated feedback, versions, and final approvals."],
    [473, "Royalty Calculation Engine", "Apply rights terms to usage and revenue statements."],
  ]),
  ...group("Agriculture Pack", "pack", "Agriculture", [
    [474, "Geospatial Field Register", "Map plots, ownership, soil profiles, and cultivation history."],
    [475, "Seasonal Crop Planner", "Schedule varieties, rotations, inputs, labor, and harvest windows."],
    [476, "Agricultural Input Inventory", "Track seed, fertilizer, chemicals, batches, and safe usage."],
    [477, "Yield Forecasting Board", "Combine field progress, weather, and historical output."],
    [478, "Grower Contract Manager", "Manage acreage, quality terms, pricing, delivery, and settlement."],
    [479, "Livestock Lifecycle Records", "Track breeding, health, movement, weight, and lineage."],
    [480, "Farm Equipment Scheduler", "Coordinate machinery bookings, operators, maintenance, and fuel."],
    [481, "Irrigation Control Calendar", "Plan water allocation by crop stage and field requirement."],
    [482, "Farm-to-Buyer Traceability", "Preserve provenance from plot and harvest to shipment."],
  ]),
  ...group("Energy Pack", "pack", "Energy", [
    [483, "Meter Account Graph", "Connect customers, premises, meters, tariffs, and service agreements."],
    [484, "Tariff Configuration Engine", "Model rates, time bands, thresholds, and regulatory changes."],
    [485, "Outage Response Center", "Correlate incidents, affected customers, crews, and restoration progress."],
    [486, "Mutual-Aid Crew Coordination", "Coordinate qualified crews, equipment, travel, and handoffs across operators."],
    [487, "Grid Asset Health Monitor", "Prioritize maintenance from condition, failure, and criticality data."],
    [488, "Renewable Certificate Register", "Track generation, ownership, transfer, retirement, and evidence."],
    [489, "Demand Response Orchestrator", "Enroll customers and manage dispatch, performance, and incentives."],
    [490, "Power Purchase Agreement Manager", "Monitor volumes, pricing, obligations, and settlement terms."],
    [491, "Emissions Accounting Ledger", "Record operational emissions, factors, offsets, and audit evidence."],
  ]),
  ...group("Public Sector Pack", "pack", "Public Sector", [
    [492, "Constituent Service Desk", "Route resident requests by jurisdiction, department, and service target."],
    [493, "Permit and License Workflow", "Manage applications, reviews, fees, issuance, and renewal."],
    [494, "Transparent Procurement Portal", "Control solicitations, evaluations, awards, contracts, and disclosures."],
    [495, "Public Grant Administration", "Manage applicants, scoring, disbursements, compliance, and outcomes."],
    [496, "Records Request Tracker", "Coordinate searches, exemptions, redaction, and statutory deadlines."],
    [497, "Mobile Inspection Suite", "Capture findings, evidence, violations, and corrective follow-ups onsite."],
    [498, "Benefits Case Manager", "Guide eligibility, evidence, decisions, renewals, and appeals."],
    [499, "Council Agenda Workspace", "Assemble submissions, approvals, minutes, votes, and public materials."],
    [500, "Emergency Coordination Board", "Unite agencies around incidents, resources, shelters, and communications."],
  ]),
];

/** Every industry pack, in the order they appear on the explorer. */
export const PACKS: string[] = [
  "Real Estate",
  "Construction",
  "Professional Services",
  "Retail and Ecommerce",
  "Healthcare",
  "Education",
  "Hospitality",
  "Legal",
  "Logistics",
  "Manufacturing",
  "Finance and Insurance",
  "Automotive",
  "Media",
  "Agriculture",
  "Energy",
  "Nonprofit",
  "Public Sector",
];

/**
 * Packs that draw on a second pack's capabilities in practice. A real-estate
 * developer running their own sites needs the construction module; a
 * dealership needs field service. Modelled here rather than duplicating
 * rows, so the catalogue stays one row per capability.
 */
export const PACK_AFFINITY: Record<string, string[]> = {
  "Real Estate": ["Construction"],
  Construction: ["Real Estate"],
  Automotive: ["Retail and Ecommerce"],
  Manufacturing: ["Logistics"],
  Logistics: ["Manufacturing"],
};

export const DOMAIN_LABEL: Record<Feature["domain"], string> = {
  crm: "CRM, growth & service",
  erp: "ERP & enterprise operations",
  pack: "Industry pack",
};

/** Ordered category list for a domain, preserving catalogue order. */
export function groupsFor(features: Feature[]): string[] {
  const seen: string[] = [];
  for (const f of features) if (!seen.includes(f.group)) seen.push(f.group);
  return seen;
}

/**
 * What a given industry's workspace covers: every horizontal capability,
 * plus that pack, plus any affinity packs.
 */
export function featuresForIndustry(pack: string | null): Feature[] {
  if (!pack) return FEATURES.filter((f) => f.pack === null);
  const allowed = new Set([pack, ...(PACK_AFFINITY[pack] ?? [])]);
  return FEATURES.filter((f) => f.pack === null || allowed.has(f.pack));
}
